#include "Game_3.h"

// STM32 HAL headers (auto-generated by STM32CubeMX)
#include "Char.h"
#include "LCD.h"
#include "Sunset_Backdrop.h"
#include "stm32l4xx_hal.h"
#include <stdint.h>
#include <stdio.h>
// #include "tim.h"    // Timer control for game timing - not currently used, using HAL_Delay instead
                       // NB! Check dif between using HAL_Delay and timer interrupts for game timing - use whichever is lighter on CPU
#include "gpio.h"      // GPIO control
#include "adc.h"       // ADC for joystick input

// Buzzer and PWM control headers - not currently used.
// #include "PWM.h"
// #include "Buzzer.h"

// AUTO-GENERATED STM32 FUNCTION PROTOTYPES - DO NOT EDIT - NB! These are copy/pasted from another lab, may need inspection if used
// void SystemClock_Config(void);
// void PeriphCommonClock_Config(void);


extern ST7789V2_cfg_t cfg0;

// Frame rate (in milliseconds)
#define GAME3_FRAME_TIME_MS 32  // ~30 FPS

GameState gamestate;
Player    player;
Bullet    bullets[MAX_BULLETS];
Enemy     enemies[MAX_ENEMIES];
Camera    camera;

MenuState Game3_Run(void) {

  InitialiseHardware();  // set up LCD, timers etc for game3 

  MenuState exit_state = MENU_STATE_HOME; // Default: return to menu
  gamestate = STATE_PLAYING; // Start at title screen --- TEMPORARILY STARTS IN STATE_PLAYING FOR TESTING GAME ENGINE ---

  // Game's own loop - runs until exit condition
  while (1) {

    uint32_t frame_start = HAL_GetTick(); // update frame timer

    ReadPlayerInput();

    switch (gamestate) {

    case STATE_TITLE:
      UpdateTitleScreen();
      RenderTitleScreen();
      break;

    case STATE_PLAYING:
      UpdatePlayState();
      RenderPlayState();
      break;

    case STATE_PAUSED:
      UpdatePauseScreen();
      RenderPauseScreen();
      break;

    case STATE_GAMEOVER:
      UpdateGameOverScreen();
      RenderGameOverScreen();
      break;

    case STATE_WIN:
      UpdateWinScreen();
      RenderWinScreen();
      break;

    }

    // Frame timing - wait for remainder of frame time - currently a blocking operation
    uint32_t frame_time = HAL_GetTick() - frame_start;
    if (frame_time < GAME3_FRAME_TIME_MS) {
      HAL_Delay(GAME3_FRAME_TIME_MS - frame_time);
    }
    // FPS display - for debugging/testing
    uint32_t total_frame_time = HAL_GetTick() - frame_start;  // includes delay from previous block
    if (total_frame_time > 0) {
      char fps_str[16];
      snprintf(fps_str, sizeof(fps_str), "FPS:%lu", 1000 / total_frame_time);
      LCD_printString(fps_str, 5, 5, 3, 2);
      LCD_Refresh(&cfg0);
    }
  }

  return exit_state; // Tell main where to go next

}

// --- Function implementations, these should mostly just call functions that are defined in their respective .c files ---
void InitialiseHardware(void) {  // set up joystick, LCD, timers etc for game3 

  Joystick_Calibrate(&joystick_cfg);  // fresh joystick calibration at start of game
  Input_Init();  // fresh init of button input system (sets up interrupts for buttons)
  LCD_Set_Palette(PALETTE_GAME3_SUNSET);  // set LCD to use chosen palette

  // --- TEMP! move to a NewGame() function later, to be called from STATE_TITLE when new game is selected ---
  player.x = 5.0f;      // a few pixels in from left edge of map
  player.y = 176.0f;    // a couple tiles up from ground level
  player.vx = 0.0f;
  player.vy = 0.0f;
  player.health = PLAYER_MAX_HEALTH;
  player.facing = 1;
  player.aim = 0;
  player.grounded = 0;
  player.shoot_cooldown = 0;
  player.anim_row = 0;
  player.anim_col = 0;
  player.anim_timer = 0;  


}

void ReadPlayerInput(void) {

  // check joystick input and update joystick_data struct:
  Joystick_Read(&joystick_cfg, &joystick_data);
  // read button input state from InputHandler.c (updated by interrupts)
  Input_Read();

}

void UpdateTitleScreen(void) {

}

void RenderTitleScreen(void) {

}

void UpdatePlayState(void) {
  // main Gameplay Loop - Reads input, updates status and position of game entities,
  // checks collisions, updates camera, checks win/loss conditions, etc

  // if (-insert pause button here-) {  // If pause button pressed, switch to pause state
  //   flag_button_pause = 0;  // Clear flag
  //   gamestate = STATE_PAUSED;
  //   return;
  // }

  UpdatePlayer(); 
  UpdateMobs();
  UpdateBullets();
  UpdateRays();

  UpdateCamera();
  CheckGameOverConditions();
  CheckWinConditions();

}

void RenderPlayState(void) {

    LCD_clear();  // Writes zeroes to frame buffer 32 bits at a time

    DrawBackground((uint8_t*)Sunset_Backdrop, SUNSET_BACKDROP_WIDTH, SUNSET_BACKDROP_HEIGHT);
    DrawTilemap((uint8_t*)Sunset_Tileset, SUNSET_TILESET_COLS);
    DrawMobs();
    DrawBullets();
    DrawRays();
    DrawPlayer((uint8_t*)CharSprite, CHAR_WIDTH);
    DrawHUD();

    LCD_Refresh(&cfg0);

}


void UpdatePauseScreen(void) {

}

void RenderPauseScreen(void) {

}

void UpdateGameOverScreen(void) {

}

void RenderGameOverScreen(void) {
  
}

void UpdateWinScreen(void) {
  
}

void RenderWinScreen(void) {
  
}

void CheckGameOverConditions(void) {

}

void CheckWinConditions(void) {

}

